version: '3'


services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./webapp/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8080:8080"
  


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web    



